<a href="https://colab.research.google.com/github/ImNotDanish05/2026_Pembelajaran-Mesin_TI-3A/blob/main/Week_3/Modul_Machine_Learning_Rev06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Kolom: x1, x2, target
data = np.array([
 [1,40,0],[2,43,0],[2,48,0],[3,50,0],[3,54,0],[4,55,0],[4,58,0],[5,60,0],
 [5,62,1],[6,60,0],[3,64,1],[6,64,1],[4,66,0],[7,63,1],[5,68,1],[7,67,1],
 [6,70,1],[8,68,1],[5,72,0],[8,72,1],[7,74,1],[9,73,1],[6,76,1],[9,76,1],
 [8,78,1],[10,77,1],[7,80,1],[10,80,1],[9,82,1],[11,81,1],[8,84,1],[11,85,1]
], dtype=float)

x1 = data[:,0]
x2 = data[:,1]
y  = data[:,2].astype(int)

z = -5.5 + 0.30*x1 + 0.065*x2
p = 1 / (1 + np.exp(-z))

def evaluate(threshold):
    pred = (p >= threshold).astype(int)
    cm = confusion_matrix(y, pred)
    tn, fp, fn, tp = cm.ravel()
    acc = accuracy_score(y, pred)
    pre = precision_score(y, pred)
    rec = recall_score(y, pred)
    f1  = f1_score(y, pred)
    spec = tn / (tn + fp)
    print('Threshold =', threshold)
    print('Confusion matrix:', cm)
    print('TN, FP, FN, TP =', tn, fp, fn, tp)
    print('Accuracy    =', round(acc,4))
    print('Precision   =', round(pre,4))
    print('Recall      =', round(rec,4))
    print('Specificity =', round(spec,4))
    print('F1-score    =', round(f1,4))
    return pred

pred05 = evaluate(0.50)
pred06 = evaluate(0.60)

print('Detail threshold 0.50')
for i in range(len(y)):
    status = ('TP' if y[i]==1 and pred05[i]==1 else
              'TN' if y[i]==0 and pred05[i]==0 else
              'FP' if y[i]==0 and pred05[i]==1 else 'FN')
    print(i+1, 'z=', round(z[i],3), 'p=', round(p[i],3),
          'aktual=', y[i], 'pred=', pred05[i], status)

Threshold = 0.5
Confusion matrix: [[ 9  2]
 [ 1 20]]
TN, FP, FN, TP = 9 2 1 20
Accuracy    = 0.9062
Precision   = 0.9091
Recall      = 0.9524
Specificity = 0.8182
F1-score    = 0.9302
Threshold = 0.6
Confusion matrix: [[10  1]
 [ 2 19]]
TN, FP, FN, TP = 10 1 2 19
Accuracy    = 0.9062
Precision   = 0.95
Recall      = 0.9048
Specificity = 0.9091
F1-score    = 0.9268
Detail threshold 0.50
1 z= -2.6 p= 0.069 aktual= 0 pred= 0 TN
2 z= -2.105 p= 0.109 aktual= 0 pred= 0 TN
3 z= -1.78 p= 0.144 aktual= 0 pred= 0 TN
4 z= -1.35 p= 0.206 aktual= 0 pred= 0 TN
5 z= -1.09 p= 0.252 aktual= 0 pred= 0 TN
6 z= -0.725 p= 0.326 aktual= 0 pred= 0 TN
7 z= -0.53 p= 0.371 aktual= 0 pred= 0 TN
8 z= -0.1 p= 0.475 aktual= 0 pred= 0 TN
9 z= 0.03 p= 0.507 aktual= 1 pred= 1 TP
10 z= 0.2 p= 0.55 aktual= 0 pred= 1 FP
11 z= -0.44 p= 0.392 aktual= 1 pred= 0 FN
12 z= 0.46 p= 0.613 aktual= 1 pred= 1 TP
13 z= -0.01 p= 0.498 aktual= 0 pred= 0 TN
14 z= 0.695 p= 0.667 aktual= 1 pred= 1 TP
15 z= 0.42 p= 0.603 aktual= 1 pred= 1 TP
16 z= 0.955 p= 0.722 aktual= 1 pred= 1 TP
17 z= 0.85 p= 0.701 aktual= 1 pred= 1 TP
18 z= 1.32 p= 0.789 aktual= 1 pred= 1 TP
19 z= 0.68 p= 0.664 aktual= 0 pred= 1 FP
20 z= 1.58 p= 0.829 aktual= 1 pred= 1 TP
21 z= 1.41 p= 0.804 aktual= 1 pred= 1 TP
22 z= 1.945 p= 0.875 aktual= 1 pred= 1 TP
23 z= 1.24 p= 0.776 aktual= 1 pred= 1 TP
24 z= 2.14 p= 0.895 aktual= 1 pred= 1 TP
25 z= 1.97 p= 0.878 aktual= 1 pred= 1 TP
26 z= 2.505 p= 0.924 aktual= 1 pred= 1 TP
27 z= 1.8 p= 0.858 aktual= 1 pred= 1 TP
28 z= 2.7 p= 0.937 aktual= 1 pred= 1 TP
29 z= 2.53 p= 0.926 aktual= 1 pred= 1 TP
30 z= 3.065 p= 0.955 aktual= 1 pred= 1 TP
31 z= 2.36 p= 0.914 aktual= 1 pred= 1 TP
32 z= 3.325 p= 0.965 aktual= 1 pred= 1 TP

In [3]:
import pandas as pd

# Create a list to store data for each row
table_data = []
for i in range(len(y)):
    status = ('TP' if y[i]==1 and pred05[i]==1 else
              'TN' if y[i]==0 and pred05[i]==0 else
              'FP' if y[i]==0 and pred05[i]==1 else 'FN')
    table_data.append({
        'No': i + 1,
        'x1': x1[i],
        'x2': x2[i],
        'z': round(z[i], 3),
        'p': round(p[i], 3),
        'Actual (y)': y[i],
        'Predicted (0.5)': pred05[i],
        'Classification': status
    })

# Convert to DataFrame and display
df_details = pd.DataFrame(table_data)
display(df_details)

    No    x1    x2      z      p  Actual (y)  Predicted (0.5) Classification
0    1   1.0  40.0 -2.600  0.069           0                0             TN
1    2   2.0  43.0 -2.105  0.109           0                0             TN
2    3   2.0  48.0 -1.780  0.144           0                0             TN
3    4   3.0  50.0 -1.350  0.206           0                0             TN
4    5   3.0  54.0 -1.090  0.252           0                0             TN
5    6   4.0  55.0 -0.725  0.326           0                0             TN
6    7   4.0  58.0 -0.530  0.371           0                0             TN
7    8   5.0  60.0 -0.100  0.475           0                0             TN
8    9   5.0  62.0  0.030  0.507           1                1             TP
9   10   6.0  60.0  0.200  0.550           0                1             FP
10  11   3.0  64.0 -0.440  0.392           1                0             FN
11  12   6.0  64.0  0.460  0.613           1                1             TP
12  13   4.0  66.0 -0.010  0.498           0                0             TN
13  14   7.0  63.0  0.695  0.667           1                1             TP
14  15   5.0  68.0  0.420  0.603           1                1             TP
15  16   7.0  67.0  0.955  0.722           1                1             TP
16  17   6.0  70.0  0.850  0.701           1                1             TP
17  18   8.0  68.0  1.320  0.789           1                1             TP
18  19   5.0  72.0  0.680  0.664           0                1             FP
19  20   8.0  72.0  1.580  0.829           1                1             TP
20  21   7.0  74.0  1.410  0.804           1                1             TP
21  22   9.0  73.0  1.945  0.875           1                1             TP
22  23   6.0  76.0  1.240  0.776           1                1             TP
23  24   9.0  76.0  2.140  0.895           1                1             TP
24  25   8.0  78.0  1.970  0.878           1                1             TP
25  26  10.0  77.0  2.505  0.924           1                1             TP
26  27   7.0  80.0  1.800  0.858           1                1             TP
27  28  10.0  80.0  2.700  0.937           1                1             TP
28  29   9.0  82.0  2.530  0.926           1                1             TP
29  30  11.0  81.0  3.065  0.955           1                1             TP
30  31   8.0  84.0  2.360  0.914           1                1             TP
31  32  11.0  85.0  3.325  0.965           1                1             TP

In [6]:
import pandas as pd
import numpy as np

table_data_new = []
for i in range(len(y)):
    table_data_new.append({
        'No': i + 1,
        'x1': x1[i],
        'x2': x2[i],
        'Actual (y)': y[i],
        'e^(-z)': round(np.exp(-z[i]), 3)
    })

# Convert to DataFrame and display
df_new_details = pd.DataFrame(table_data_new)
display(df_new_details)

    No    x1    x2  Actual (y)  e^(-z)
0    1   1.0  40.0           0  13.464
1    2   2.0  43.0           0   8.207
2    3   2.0  48.0           0   5.930
3    4   3.0  50.0           0   3.857
4    5   3.0  54.0           0   2.974
5    6   4.0  55.0           0   2.065
6    7   4.0  58.0           0   1.699
7    8   5.0  60.0           0   1.105
8    9   5.0  62.0           1   0.970
9   10   6.0  60.0           0   0.819
10  11   3.0  64.0           1   1.553
11  12   6.0  64.0           1   0.631
12  13   4.0  66.0           0   1.010
13  14   7.0  63.0           1   0.499
14  15   5.0  68.0           1   0.657
15  16   7.0  67.0           1   0.385
16  17   6.0  70.0           1   0.427
17  18   8.0  68.0           1   0.267
18  19   5.0  72.0           0   0.507
19  20   8.0  72.0           1   0.206
20  21   7.0  74.0           1   0.244
21  22   9.0  73.0           1   0.143
22  23   6.0  76.0           1   0.289
23  24   9.0  76.0           1   0.118
24  25   8.0  78.0           1   0.139
25  26  10.0  77.0           1   0.082
26  27   7.0  80.0           1   0.165
27  28  10.0  80.0           1   0.067
28  29   9.0  82.0           1   0.080
29  30  11.0  81.0           1   0.047
30  31   8.0  84.0           1   0.094
31  32  11.0  85.0           1   0.036